import { CityEnum, ShelterEnum } from "@app/typings/enum";

export const ShelterMapByArea: { [key in string]: string } = {
  [CityEnum.TPE.toString()]: ShelterEnum.TPE.toString(),
  [CityEnum.TPH.toString()]: ShelterEnum.TPH01.toString(),
  [CityEnum.KLU.toString()]: ShelterEnum.KLU.toString(),
  [CityEnum.ILN.toString()]: ShelterEnum.ILN.toString(),
  [CityEnum.TYC.toString()]: ShelterEnum.TYC.toString(),
  [CityEnum.HSH.toString()]: ShelterEnum.HSH.toString(),
  [CityEnum.HSC.toString()]: ShelterEnum.HSC.toString(),
  [CityEnum.MAL.toString()]: ShelterEnum.MAL.toString(),
  [CityEnum.TXG.toString()]: ShelterEnum.TXG01.toString(),
  [CityEnum.CWH.toString()]: ShelterEnum.CWH.toString(),
  [CityEnum.NTO.toString()]: ShelterEnum.NTO.toString(),
  [CityEnum.YLH.toString()]: ShelterEnum.YLH.toString(),
  [CityEnum.CHY.toString()]: ShelterEnum.CHY.toString(),
  [CityEnum.CYI.toString()]: ShelterEnum.CYI.toString(),
  [CityEnum.TNN.toString()]: ShelterEnum.TNN01.toString(),
  [CityEnum.KHH.toString()]: ShelterEnum.KHH01.toString(),
  [CityEnum.IUH.toString()]: ShelterEnum.IUH.toString(),
  [CityEnum.HWA.toString()]: ShelterEnum.HWA.toString(),
  [CityEnum.TTT.toString()]: ShelterEnum.TTT.toString(),
  [CityEnum.PEH.toString()]: ShelterEnum.PEH.toString(),
  [CityEnum.KMN.toString()]: ShelterEnum.KMN.toString(),
  [CityEnum.LNN.toString()]: ShelterEnum.LNN.toString(),
};

export const AreaMapByShelter: { [key in string]: string } = {
  [ShelterEnum.KLU.toString()]: CityEnum.KLU.toString(),
  [ShelterEnum.TPE.toString()]: CityEnum.TPE.toString(),
  [ShelterEnum.TPH01.toString()]: CityEnum.TPH.toString(),
  [ShelterEnum.TPH02.toString()]: CityEnum.TPH.toString(),
  [ShelterEnum.TPH03.toString()]: CityEnum.TPH.toString(),
  [ShelterEnum.TPH04.toString()]: CityEnum.TPH.toString(),
  [ShelterEnum.TPH05.toString()]: CityEnum.TPH.toString(),
  [ShelterEnum.TPH06.toString()]: CityEnum.TPH.toString(),
  [ShelterEnum.TPH07.toString()]: CityEnum.TPH.toString(),
  [ShelterEnum.TPH08.toString()]: CityEnum.TPH.toString(),
  [ShelterEnum.TPH09.toString()]: CityEnum.TPH.toString(),
  [ShelterEnum.TYC.toString()]: CityEnum.TYC.toString(),
  [ShelterEnum.HSC.toString()]: CityEnum.HSC.toString(),
  [ShelterEnum.HSH.toString()]: CityEnum.HSH.toString(),
  [ShelterEnum.TXG01.toString()]: CityEnum.TXG.toString(),
  [ShelterEnum.TXG02.toString()]: CityEnum.TXG.toString(),
  [ShelterEnum.CWH.toString()]: CityEnum.CWH.toString(),
  [ShelterEnum.NTO.toString()]: CityEnum.NTO.toString(),
  [ShelterEnum.CYI.toString()]: CityEnum.CYI.toString(),
  [ShelterEnum.CHY.toString()]: CityEnum.CHY.toString(),
  [ShelterEnum.TNN01.toString()]: CityEnum.TNN.toString(),
  [ShelterEnum.TNN02.toString()]: CityEnum.TNN.toString(),
  [ShelterEnum.KHH01.toString()]: CityEnum.KHH.toString(),
  [ShelterEnum.KHH02.toString()]: CityEnum.KHH.toString(),
  [ShelterEnum.IUH.toString()]: CityEnum.IUH.toString(),
  [ShelterEnum.ILN.toString()]: CityEnum.ILN.toString(),
  [ShelterEnum.HWA.toString()]: CityEnum.HWA.toString(),
  [ShelterEnum.TTT.toString()]: CityEnum.TTT.toString(),
  [ShelterEnum.LNN.toString()]: CityEnum.LNN.toString(),
  [ShelterEnum.KMN.toString()]: CityEnum.KMN.toString(),
  [ShelterEnum.PEH.toString()]: CityEnum.PEH.toString(),
  [ShelterEnum.YLH.toString()]: CityEnum.YLH.toString(),
  [ShelterEnum.MAL.toString()]: CityEnum.MAL.toString(),
};
